//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_fun_world_4_final.html
halflife.wad
gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
maps/zm_fun_world_4_final.bsp
